name: Soc
description: Solved Consultancy Ed-Tech Platfrom

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0

environment:
  sdk: '>=2.14.0 <3.0.0' #'>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
   sdk: flutter  
  cupertino_icons: ^1.0.3
  intl: ^0.17.0
  shared_preferences: ^2.0.6
  flutter_bloc: ^7.0.1
  http: ^0.13.4
  equatable: ^2.0.3
  webview_flutter: ^2.5.0
  modal_bottom_sheet: ^2.0.0
  cached_network_image: ^3.0.0
  device_info: ^2.0.2
  xml2json: ^5.3.1
  dio: ^4.0.0
  url_launcher: ^6.0.10 #^6.0.12
  permission_handler: ^8.3.0
  flutter_downloader: ^1.7.2
  share: ^2.0.4
  image_picker: ^0.8.1+3
  google_maps_flutter: ^2.0.6
  onesignal_flutter: ^3.2.3
  table_calendar: ^3.0.1
  flutter_datetime_picker: ^1.5.1
  html: ^0.15.0
  flutter_html: ^2.2.1
  # flutter_html: ^2.1.5
  flutter_linkify: ^5.0.2
  advance_pdf_viewer: 2.0.0
  hive: ^2.0.4
  hive_generator: ^1.1.0
  build_runner: ^2.0.6
  add_2_calendar: ^2.1.3
  font_awesome_flutter: ^9.1.0
  package_info_plus: ^1.4.0
  html_unescape: ^2.0.0
  persistent_bottom_nav_bar: ^4.0.2
  flutter_oss_licenses: ^1.0.1
  shimmer: ^2.0.0
  # adaptive_theme: ^2.2.0
  adaptive_theme: ^2.3.1
  flutter_offline: ^2.0.0
  flutter_svg: ^0.23.0+1
  mailto: ^2.0.0
  marquee: ^2.2.0
  open_apps_settings: ^0.0.4
  like_button: ^2.0.3
  bubble_showcase:
    git:
      url: https://github.com/piyushrathodIn/BubbleShowcase.git
      ref: onfinished_callback
  photo_view: ^0.13.0  
  speech_bubble: ^0.0.9
  # firebase_analytics: ^8.3.3 
  invert_colors: ^0.0.4
  path_provider: ^2.0.8
  new_version: ^0.2.3
  flutter_math_fork : ^0.5.0 #^0.4.2+1 #
  back_button_interceptor: ^5.0.2
  auto_orientation: ^2.2.1
  camera: ^0.9.4+16 
  google_ml_kit: ^0.7.3
  flutter_mobile_vision: ^0.1.4+1

  googleapis: ^7.0.0
  google_sign_in: ^5.2.1
  googleapis_auth: ^1.3.1
  firebase_auth: ^3.3.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
 

flutter_icons:
  image_path: "assets/images/appicon.png"  
  android: true
  ios: true
     
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/locale/localization_en.json
    # - assets/locale/localization_nl.json
    - assets/images/
    

  # An image asset can refer to one or more resolution-specific "finaliants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Italic.ttf
        - asset: fonts/Roboto-Bold.ttf
        # - asset: fonts/Roboto-SemiBold.ttf
    - family: SOC_CustomIcons
      fonts:
        - asset: fonts/CustomFlutterIcons.ttf    
        
 
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
