// /// Flutter icons PBISPlusIcons
// /// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
// /// This font was generated by FlutterIcon.com, which is derived from Fontello.
// ///
// /// To use this font, place it in your fonts/ directory and include the
// /// following in your pubspec.yaml
// ///
// /// flutter:
// ///   fonts:
// ///    - family:  PBISPlusIcons
// ///      fonts:
// ///       - asset: fonts/PBISPlusIcons.ttf
// ///
// ///
// ///
// import 'package:flutter/widgets.dart';

// class PBISPlusIcons {
//   PBISPlusIcons._();

//   static const _kFontFam = 'PBISPlusIcons';
//   static const String? _kFontPkg = null;

//   static const IconData PBISPlus_plus_history =
//       IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData PBISPlus_plus_class =
//       IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData PBISPlus_plus_settings =
//       IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData PBISPlus_plus_floating =
//       IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData backarrow_icon_1 =
//       IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData spin3 =
//       IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData filter =
//       IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData like =
//       IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData thanks =
//       IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData help =
//       IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData eye1 =
//       IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
// }
