/// Flutter icons CustomFlutterIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomFlutterIcons
///      fonts:
///       - asset: fonts/CustomFlutterIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class CustomFlutterIcons {
  CustomFlutterIcons._();

  static const _kFontFam = 'CustomFlutterIcons';
  static const String? _kFontPkg = null;

  static const IconData group_60 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData news_iocn = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nyc_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resource_icon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData school_merchandise_icon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_icons = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting_icon = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData social_icon = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData staff_icon = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData staffdirectory_icon = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData student_icon = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData about_us_icon = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_deactive = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backarrow_icon = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData openinweb_icon = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reload_icon = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_icons = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comp_emrgency_icon = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact_icons = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData families_icon = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forms_icon = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward_arrow_icon = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gradebook_icon = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health_icon = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter_logo_icon = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_icon = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error_icon = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_data_icon = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_internet_icon = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData translate_logo_max_500x500 = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_7_2x = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_6_2x = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_7_2x_1 = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_2_copy_2_1x = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_like_70067_1x = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData path_2x = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blue = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blue_1 = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blue_2 = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData v1 = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData after_school = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData athletics = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clubs = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData donate = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forms = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pta = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sports = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData student_council = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData support = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_to_calendar = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData open_browser = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
